os: Visual Studio 2019

# Clone directly into GOPATH.
clone_folder: C:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GO111MODULE: on
  matrix:
    - GETH_ARCH: amd64
      CC: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\bin\gcc.exe
      PATH: C:\Program Files (x86)\NSIS\;%PATH%
    - GETH_ARCH: 386
      CC: C:\msys64\mingw32\bin\gcc.exe
      PATH: C:\Program Files (x86)\NSIS\;%PATH%

install:
  - git submodule update --init
  - go version
  - "%CC% --version"

build_script:
  - go run build\ci.go install -dlgo -arch %GETH_ARCH%

after_build:
  - go run build\ci.go archive -arch %GETH_ARCH% -type zip -signer WINDOWS_SIGNING_KEY -upload gethstore/builds
  - go run build\ci.go nsis -arch %GETH_ARCH% -signer WINDOWS_SIGNING_KEY -upload gethstore/builds

test_script:
  - go run build\ci.go test -dlgo -arch %GETH_ARCH% -coverage
