os: Visual Studio 2019

# Clone directly into GOPATH.
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GO111MODULE: on
  matrix:
    - GETH_ARCH: amd64
      MINGW_DIR: x86_64-8.1.0-posix-seh-rt_v6-rev0
    - GETH_ARCH: 386
      MINGW_DIR: i686-8.1.0-posix-dwarf-rt_v6-rev0

install:
  # - git submodule update --init
  - dir C:\mingw-w64\%MINGW_DIR%\mingw64
  - dir C:\mingw-w64\%MINGW_DIR%\mingw64\bin
  - set PATH=C:\mingw-w64\%MINGW_DIR%\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
  - go version
  - gcc --version

build_script:
  - go run build\ci.go install -dlgo

after_build:
  - go run build\ci.go archive -type zip -signer WINDOWS_SIGNING_KEY -upload gethstore/builds
  - go run build\ci.go nsis -signer WINDOWS_SIGNING_KEY -upload gethstore/builds

test_script:
  - set CGO_ENABLED=1
  - go run build\ci.go test -coverage
