os: Visual Studio 2019

# Clone directly into GOPATH.
clone_folder: C:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GO111MODULE: on
    GOPATH: C:\gopath
    CC: gcc.exe
  matrix:
    # - GETH_ARCH: amd64
    #   MSYS2_ARCH: x86_64
    #   MSYS2_BITS: 64
    #   MSYSTEM: MINGW64
    #   PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
    - GETH_ARCH: 386
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
    #   MSYS2_ARCH: i686
    #   MSYS2_BITS: 32
    #   MSYSTEM: MINGW32


install:
  - git submodule update --init
  - go version
  - gcc --version

build_script:
  - go run build\ci.go install -dlgo -arch %GETH_ARCH% -cc C:\msys64\mingw32\bin\gcc.exe

after_build:
  - go run build\ci.go archive -arch %GETH_ARCH% -type zip -signer WINDOWS_SIGNING_KEY -upload gethstore/builds
  - go run build\ci.go nsis -arch %GETH_ARCH% -signer WINDOWS_SIGNING_KEY -upload gethstore/builds

test_script:
  - go run build\ci.go test -dlgo -arch %GETH_ARCH% -coverage
